### ISSUE TITLE
No clear link between the git repository and the website.

### ISSUE THREAD

**Issue by Justinfront** [jiveui/jive#109]
When I search for 'haxe jive' on google I get.
(https://github.com/jiveui/jive/)
But the readme on the repository does not contain an **image** and links to:
http://jiveui.github.io/index.html
or to 
http://jiveui.github.io/jive/
If I go to your nice website there is no "fork" icon or any obvious link to the repository I realize they are both on github but I still think there is some continuity in presentation missing by these two subtle ommisions.  

( Curious do unit tests also cover NME as well as OpenFL, because I believe svg support in NME is good and often setup for NME is very reliable ?  Looking at a few classes in the source it seems it might be hard to support other haxe frameworks do you have some thoughts on this? ).

**Comment by ngrebenshikov** [comment]
We've added links to the github page and to the site. Thank you for the issue.

Regarding, NME. I think its important to support it. Regarding others it's not the case right now.
