### ISSUE TITLE
Cat't build gestures/SwipeGesture class

### ISSUE THREAD

**Issue by shooter0106** [jiveui/jive#112]
Hello!
I have a problem while build a scroll application from jive-examples using "cpp" target:

>Error: While running :g++ -I/home/shooter/tmp/jive-examples/scroll/bin/linux64/cpp/release/obj/obj/linux64/__pch/haxe -Iinclude -c -fvisibility=hidden -O2 -fpic -fPI
C -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,3,49/include -x c++ -frtti -Wno-invalid-offsetof ./s
rc/jive/gestures/SwipeGesture.cpp -o/home/shooter/tmp/jive-examples/scroll/bin/linux64/cpp/release/obj/obj/linux64/30c0776f_SwipeGesture.o
./src/jive/gestures/SwipeGesture.cpp: In static member function ‘static void jive::gestures::SwipeGesture_obj::__boot()’:
./src/jive/gestures/SwipeGesture.cpp:884:28: error: expected primary-expression before ‘if’
 HXDLIN(  33)  MIN_OFFSET = if ((_hx_tmp > (int)0)) {
                            ^~
./src/jive/gestures/SwipeGesture.cpp:888:15: error: ‘else’ without a previous ‘if’
               else {
               ^~~~

I have a Haxe Compiler 3.3.0 and this packakages:

> actuate: [1.8.7]
bindx2: [2.5.2]
box2d: [1.2.3]
hml: [0.0.2-alpha]
hxcpp: [3.3.49]
jive: [git]
layout: [1.2.1]
lime-samples: [3.4.0]
lime: 3.0.0 3.1.0 3.2.0 [3.2.1] 3.3.0 3.4.1
openfl-samples: [4.4.0]
openfl: [4.2.0] 4.4.1
svg: [1.1.1]
swf: [2.3.1]
unifill: [0.4.1]

Console output: http://pastebin.com/xaLQXk7B

it is jive or hxcpp problem?
Thanks.

**Comment by ngrebenshikov** [comment]
Hi,

we’ve tried to compile Jive with have 3.3. May be it’s the cause. Could you try with 3.2?

**Comment by shooter0106** [comment]
Yep, with Haxe 3.2.1 build is successful finished. But resulted executable is broken: get a segfault.
