### ISSUE TITLE
JTextField: the first character isn't showed

### ISSUE THREAD

**Issue by ngrebenshikov** [jiveui/jive#77]

**Comment by PhiLhoSoft** [comment]
I tested quickly the demo, and indeed the first character I typed in the Text fields demo wasn't shown, until I typed another char.

It is also lacking a caret when we focus on an empty field, there is no way to click on a location to move the caret, Ctrl+arrow and Ctrl+Backspace (act on words) don't work, selection leaves the caret where it is (unusual!) and is strangely managed (Del doesn't work, BS is inconsistent).

I stop here, obviously there is still much work to do here... :smile: 
Good work overall, doing such library is a big task!
